### ISSUE TITLE
Disappearing/Crashing when mathematical operations are inputed 

### ISSUE THREAD

**Issue by rahulc07** [marvelman3284/derivative-generator#1]
This might help?

`SyntaxError: Unexpected end of expression (char 2)
    fe parse.js:1616
    t parse.js:1581
    t parse.js:1570
    t parse.js:1543
    t parse.js:1527
    t parse.js:1459
    t parse.js:1375
    t parse.js:1331
    t parse.js:1230
    t parse.js:1203
    t parse.js:1127
    ie parse.js:1109
    ie parse.js:1098
    ie parse.js:1095
    ne parse.js:1058
    te parse.js:1009
    ee parse.js:981
    J parse.js:951
    X parse.js:924
    Y parse.js:886
    W parse.js:851
    V parse.js:828
    $ parse.js:792
    H parse.js:778
    L parse.js:763
    R parse.js:748
    I parse.js:733
    q parse.js:718
    t parse.js:703
    a parse.js:674
    z parse.js:627
    r parse.js:575
    k parse.js:546
    string parse.js:70
    me typed-function.mjs:1790
    cM validate.ts:13
    fM App.tsx:16
    React 14
[react-dom.production.min.js:189:29](https://math.sevenlayer.org/static/node_modules/react-dom/cjs/react-dom.production.min.js)
Uncaught SyntaxError: Unexpected end of expression (char 2)
    fe parse.js:1616
    t parse.js:1581
    t parse.js:1570
    t parse.js:1543
    t parse.js:1527
    t parse.js:1459
    t parse.js:1375
    t parse.js:1331
    t parse.js:1230
    t parse.js:1203
    t parse.js:1127
    ie parse.js:1109
    ie parse.js:1098
    ie parse.js:1095
    ne parse.js:1058
    te parse.js:1009
    ee parse.js:981
    J parse.js:951
    X parse.js:924
    Y parse.js:886
    W parse.js:851
    V parse.js:828
    $ parse.js:792
    H parse.js:778
    L parse.js:763
    R parse.js:748
    I parse.js:733
    q parse.js:718
    t parse.js:703
    a parse.js:674
    z parse.js:627
    r parse.js:575
    k parse.js:546
    string parse.js:70
    me typed-function.mjs:1790
    cM validate.ts:13
    fM App.tsx:16
    React 14
[parse.js:1616:16](https://math.sevenlayer.org/static/node_modules/mathjs/lib/esm/expression/parse.js)`

(Console output whenever a mathematical operation is used)

Proven that it is not just my computer Jeevan.

Host:
Firefox 117.0.1 on  
Linux From Scratch 12.0-179/Tucana 3.0-beta-2.  See https://www.linuxfromscratch.org/blfs/view/systemd/ on how to use a real Linux system if you are an Arch btw user.  
Desktop: i3 on X11

Tested on Chrome 117 as well, same problem.

I'll do a pull if I have time, probably won't

Have fun!
-- Rahul

**Comment by jeevanshah07** [comment]
Thanks for the issue but I figured out the error last night. Updates just haven't been made to the site yet due to failing ci/cd

**Comment by jeevanshah07** [comment]
See [this commit](https://github.com/marvelman3284/derivative-generator/commit/23c31ffccda0c6de1c057438082585ee66cd49ac) and src/helpers/validate.ts for the fix

**Comment by rahulc07** [comment]
Cool, good job getting it fixed.
